-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\MSDB_Control\Control_Sub.vhd
-- Created: 2022-02-04 15:03:05
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Control_Sub
-- Source Path: MSDB_Control/Control_Sub
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Control_Sub IS
  PORT( Omega_Rpm_Digital                 :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        Count_2500                        :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        Id                                :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        Iq                                :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        Idref                             :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        Iqref                             :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        U1MDBd                            :   OUT   std_logic_vector(15 DOWNTO 0);  -- int16
        U1MDBq                            :   OUT   std_logic_vector(15 DOWNTO 0)  -- int16
        );
END Control_Sub;


ARCHITECTURE rtl OF Control_Sub IS

  -- Component Declarations
  COMPONENT Dig_Ang
    PORT( rpm_Digital_16bit               :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
          omega_Analog                    :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En16
          );
  END COMPONENT;

  COMPONENT limit_Tc_and_no_limit_Tc
    PORT( Tc_count_2500                   :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          limit_Tc                        :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32_En32
          no_limit_Tc                     :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32_En32
          );
  END COMPONENT;

  COMPONENT invG
    PORT( omega_Analog                    :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          limit_Tc                        :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32_En32
          no_limit_Tc                     :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32_En32
          invG11                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          invG12                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
          invG21                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
          invG22                          :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En16
          );
  END COMPONENT;

  COMPONENT invGF
    PORT( omega_Analog                    :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          limit_Tc                        :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32_En32
          no_limit_Tc                     :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32_En32
          invGF11                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          invGF12                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
          invGF21                         :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
          invGF22                         :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En16
          );
  END COMPONENT;

  COMPONENT Vdq_ref
    PORT( invG11                          :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          invG12                          :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
          invG21                          :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
          invG22                          :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          invGF11                         :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          invGF12                         :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
          invGF21                         :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
          invGF22                         :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          Id                              :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
          Iq                              :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
          Idref                           :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
          Iqref                           :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
          Omega_Sgn                       :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          Vd                              :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          Vq                              :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En16
          );
  END COMPONENT;

  COMPONENT PWM_Gain
    PORT( Vd                              :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          Vq                              :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
          U1MDBd                          :   OUT   std_logic_vector(15 DOWNTO 0);  -- int16
          U1MDBq                          :   OUT   std_logic_vector(15 DOWNTO 0)  -- int16
          );
  END COMPONENT;

--  -- Component Configuration Statements
--  FOR ALL : Dig_Ang
--    USE ENTITY work.Dig_Ang(rtl);
--
--  FOR ALL : limit_Tc_and_no_limit_Tc
--    USE ENTITY work.limit_Tc_and_no_limit_Tc(rtl);
--
--  FOR ALL : invG
--    USE ENTITY work.invG(rtl);
--
--  FOR ALL : invGF
--    USE ENTITY work.invGF(rtl);
--
--  FOR ALL : Vdq_ref
--    USE ENTITY work.Vdq_ref(rtl);
--
--  FOR ALL : PWM_Gain
--    USE ENTITY work.PWM_Gain(rtl);

  -- Signals
  SIGNAL omega_Analog                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL limit_Tc                         : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL no_limit_Tc                      : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL invG_out1                        : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL invG_out2                        : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL invG_out3                        : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL invG_out4                        : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL invGF_out1                       : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL invGF_out2                       : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL invGF_out3                       : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL invGF_out4                       : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Vdq_ref_out1                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL Vdq_ref_out2                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL PWM_Gain_out1                    : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL PWM_Gain_out2                    : std_logic_vector(15 DOWNTO 0);  -- ufix16

BEGIN
  u_Dig_Ang : Dig_Ang
    PORT MAP( rpm_Digital_16bit => Omega_Rpm_Digital,  -- int16
              omega_Analog => omega_Analog  -- sfix32_En16
              );

  u_limit_Tc_and_no_limit_Tc : limit_Tc_and_no_limit_Tc
    PORT MAP( Tc_count_2500 => Count_2500,  -- uint16
              limit_Tc => limit_Tc,  -- ufix32_En32
              no_limit_Tc => no_limit_Tc  -- ufix32_En32
              );

  u_invG : invG
    PORT MAP( omega_Analog => omega_Analog,  -- sfix32_En16
              limit_Tc => limit_Tc,  -- ufix32_En32
              no_limit_Tc => no_limit_Tc,  -- ufix32_En32
              invG11 => invG_out1,  -- sfix32_En16
              invG12 => invG_out2,  -- sfix32_En28
              invG21 => invG_out3,  -- sfix32_En28
              invG22 => invG_out4  -- sfix32_En16
              );

  u_invGF : invGF
    PORT MAP( omega_Analog => omega_Analog,  -- sfix32_En16
              limit_Tc => limit_Tc,  -- ufix32_En32
              no_limit_Tc => no_limit_Tc,  -- ufix32_En32
              invGF11 => invGF_out1,  -- sfix32_En16
              invGF12 => invGF_out2,  -- sfix32_En28
              invGF21 => invGF_out3,  -- sfix32_En28
              invGF22 => invGF_out4  -- sfix32_En16
              );

  u_Vdq_ref : Vdq_ref
    PORT MAP( invG11 => invG_out1,  -- sfix32_En16
              invG12 => invG_out2,  -- sfix32_En28
              invG21 => invG_out3,  -- sfix32_En28
              invG22 => invG_out4,  -- sfix32_En16
              invGF11 => invGF_out1,  -- sfix32_En16
              invGF12 => invGF_out2,  -- sfix32_En28
              invGF21 => invGF_out3,  -- sfix32_En28
              invGF22 => invGF_out4,  -- sfix32_En16
              Id => Id,  -- int16
              Iq => Iq,  -- int16
              Idref => Idref,  -- int16
              Iqref => Iqref,  -- int16
              Omega_Sgn => omega_Analog,  -- sfix32_En16
              Vd => Vdq_ref_out1,  -- sfix32_En16
              Vq => Vdq_ref_out2  -- sfix32_En16
              );

  u_PWM_Gain : PWM_Gain
    PORT MAP( Vd => Vdq_ref_out1,  -- sfix32_En16
              Vq => Vdq_ref_out2,  -- sfix32_En16
              U1MDBd => PWM_Gain_out1,  -- int16
              U1MDBq => PWM_Gain_out2  -- int16
              );

  U1MDBd <= PWM_Gain_out1;

  U1MDBq <= PWM_Gain_out2;

END rtl;

