-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\MSDB_Control\Dig_Ang.vhd
-- Created: 2022-02-04 15:03:05
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Dig_Ang
-- Source Path: MSDB_Control/Control_Sub/Dig->Ang
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Dig_Ang IS
  PORT( rpm_Digital_16bit                 :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        omega_Analog                      :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En16
        );
END Dig_Ang;


ARCHITECTURE rtl OF Dig_Ang IS

  -- Signals
  SIGNAL rpm_Digital_16bit_signed         : signed(15 DOWNTO 0);  -- int16
  SIGNAL used_for_DArpm_out1              : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL rpm_Analog_mul_temp              : signed(33 DOWNTO 0);  -- sfix34_En16
  SIGNAL rpm_Analog_out1                  : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL used_for_omega                   : signed(17 DOWNTO 0);  -- sfix18_En16
  SIGNAL conversion_to_omega_mul_temp     : signed(49 DOWNTO 0);  -- sfix50_En32
  SIGNAL conversion_to_omega_out1         : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL Gain_cast                        : signed(63 DOWNTO 0);  -- sfix64_En44
  SIGNAL Gain_out1                        : signed(31 DOWNTO 0);  -- sfix32_En16

BEGIN
  rpm_Digital_16bit_signed <= signed(rpm_Digital_16bit);

  used_for_DArpm_out1 <= to_signed(16#01F40#, 18);

  rpm_Analog_mul_temp <= rpm_Digital_16bit_signed * used_for_DArpm_out1;
  rpm_Analog_out1 <= rpm_Analog_mul_temp(31 DOWNTO 0);

  used_for_omega <= to_signed(16#01ACF#, 18);

  conversion_to_omega_mul_temp <= rpm_Analog_out1 * used_for_omega;
  conversion_to_omega_out1 <= conversion_to_omega_mul_temp(47 DOWNTO 16);

  Gain_cast <= resize(conversion_to_omega_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 64);
  Gain_out1 <= Gain_cast(59 DOWNTO 28);

  omega_Analog <= std_logic_vector(Gain_out1);

END rtl;

