-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\MSDB_Control\invG.vhd
-- Created: 2022-02-04 15:03:05
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: invG
-- Source Path: MSDB_Control/Control_Sub/invG
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY invG IS
  PORT( omega_Analog                      :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        limit_Tc                          :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32_En32
        no_limit_Tc                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32_En32
        invG11                            :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        invG12                            :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
        invG21                            :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
        invG22                            :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En16
        );
END invG;


ARCHITECTURE rtl OF invG IS

  -- Signals
  SIGNAL G11_b_out1                       : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL G11_a_out1                       : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL limit_Tc_unsigned                : unsigned(31 DOWNTO 0);  -- ufix32_En32
  SIGNAL for_G11_G22_out1                 : unsigned(31 DOWNTO 0);  -- ufix32_En16
  SIGNAL G11_Multiply_Tc_mul_temp         : unsigned(47 DOWNTO 0);  -- ufix48_En32
  SIGNAL G11_Multiply_Tc_out1             : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL G11_Sum_add_cast                 : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL G11_Sum_add_cast_1               : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL G11_Sum_add_temp                 : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL G11_Sum_out1                     : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL G12_c_out1                       : unsigned(7 DOWNTO 0);  -- ufix8_En16
  SIGNAL G12_a_out1                       : unsigned(20 DOWNTO 0);  -- ufix21_En16
  SIGNAL no_limit_Tc_unsigned             : unsigned(31 DOWNTO 0);  -- ufix32_En32
  SIGNAL G12_Mulitiply_Tc_mul_temp        : unsigned(52 DOWNTO 0);  -- ufix53_En48
  SIGNAL G12_Mulitiply_Tc_out1            : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL G12_Sum_stage2_sub_cast          : signed(32 DOWNTO 0);  -- sfix33_En24
  SIGNAL G12_Sum_stage2_sub_cast_1        : signed(32 DOWNTO 0);  -- sfix33_En24
  SIGNAL G12_Sum_op_stage2                : signed(32 DOWNTO 0);  -- sfix33_En24
  SIGNAL G12_b_out1                       : unsigned(4 DOWNTO 0);  -- ufix5_En16
  SIGNAL omega_Analog_signed              : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL G12_Multiply_o_cast              : signed(5 DOWNTO 0);  -- sfix6_En16
  SIGNAL G12_Multiply_o_mul_temp          : signed(37 DOWNTO 0);  -- sfix38_En32
  SIGNAL G12_Multiply_o_cast_1            : signed(36 DOWNTO 0);  -- sfix37_En32
  SIGNAL G12_Multiply_o_out1              : signed(19 DOWNTO 0);  -- sfix20_En16
  SIGNAL G12_Sum_stage3_sub_cast          : signed(32 DOWNTO 0);  -- sfix33_En24
  SIGNAL G12_Sum_stage3_sub_temp          : signed(32 DOWNTO 0);  -- sfix33_En24
  SIGNAL G12_Sum_out1                     : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL G21_a_out1                       : unsigned(31 DOWNTO 0);  -- ufix32_En16
  SIGNAL G21_Mulitiply_Tc_mul_temp        : unsigned(63 DOWNTO 0);  -- ufix64_En48
  SIGNAL G21_Mulitiply_Tc_out1            : unsigned(23 DOWNTO 0);  -- ufix24_En24
  SIGNAL G21_b_out1                       : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL G21_Multiply_o_cast              : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL G21_Multiply_o_mul_temp          : signed(48 DOWNTO 0);  -- sfix49_En32
  SIGNAL G21_Multiply_o_cast_1            : signed(47 DOWNTO 0);  -- sfix48_En32
  SIGNAL G21_Multiply_o_out1              : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL G21_Sum_stage2_add_cast          : signed(25 DOWNTO 0);  -- sfix26_En24
  SIGNAL G21_Sum_stage2_add_cast_1        : signed(25 DOWNTO 0);  -- sfix26_En24
  SIGNAL G21_Sum_op_stage2                : signed(25 DOWNTO 0);  -- sfix26_En24
  SIGNAL G21_c_out1                       : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL G21_Sum_stage3_sub_cast          : signed(25 DOWNTO 0);  -- sfix26_En24
  SIGNAL G21_Sum_stage3_sub_temp          : signed(25 DOWNTO 0);  -- sfix26_En24
  SIGNAL G21_Sum_out1                     : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL G22_a_out1                       : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL G22_Multiply_Tc_mul_temp         : unsigned(47 DOWNTO 0);  -- ufix48_En32
  SIGNAL G22_Multiply_Tc_out1             : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL G22_b_out1                       : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL G22_Sum_add_cast                 : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL G22_Sum_add_cast_1               : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL G22_Sum_add_temp                 : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL G22_Sum_out1                     : signed(31 DOWNTO 0);  -- sfix32_En16

BEGIN
  G11_b_out1 <= to_unsigned(16#BB09#, 16);

  G11_a_out1 <= to_unsigned(16#01C7#, 16);

  limit_Tc_unsigned <= unsigned(limit_Tc);

  for_G11_G22_output : PROCESS (limit_Tc_unsigned)
    VARIABLE c : unsigned(48 DOWNTO 0);
    VARIABLE div_temp : unsigned(48 DOWNTO 0);
  BEGIN
    div_temp := to_unsigned(0, 49);
    IF limit_Tc_unsigned = to_unsigned(0, 32) THEN 
      c := unsigned'("1111111111111111111111111111111111111111111111111");
    ELSE 
      div_temp := unsigned'("1000000000000000000000000000000000000000000000000") / limit_Tc_unsigned;
      c := div_temp;
    END IF;
    IF c(48 DOWNTO 32) /= "00000000000000000" THEN 
      for_G11_G22_out1 <= X"FFFFFFFF";
    ELSE 
      for_G11_G22_out1 <= c(31 DOWNTO 0);
    END IF;
  END PROCESS for_G11_G22_output;


  G11_Multiply_Tc_mul_temp <= G11_a_out1 * for_G11_G22_out1;
  G11_Multiply_Tc_out1 <= signed(G11_Multiply_Tc_mul_temp(47 DOWNTO 16));

  G11_Sum_add_cast <= signed(resize(G11_b_out1, 33));
  G11_Sum_add_cast_1 <= resize(G11_Multiply_Tc_out1, 33);
  G11_Sum_add_temp <= G11_Sum_add_cast + G11_Sum_add_cast_1;
  G11_Sum_out1 <= G11_Sum_add_temp(31 DOWNTO 0);

  invG11 <= std_logic_vector(G11_Sum_out1);

  G12_c_out1 <= to_unsigned(16#BC#, 8);

  G12_a_out1 <= to_unsigned(16#1C8F5C#, 21);

  no_limit_Tc_unsigned <= unsigned(no_limit_Tc);

  G12_Mulitiply_Tc_mul_temp <= G12_a_out1 * no_limit_Tc_unsigned;
  G12_Mulitiply_Tc_out1 <= signed(resize(G12_Mulitiply_Tc_mul_temp(52 DOWNTO 24), 32));

  G12_Sum_stage2_sub_cast <= signed(resize(G12_c_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 33));
  G12_Sum_stage2_sub_cast_1 <= resize(G12_Mulitiply_Tc_out1, 33);
  G12_Sum_op_stage2 <= G12_Sum_stage2_sub_cast - G12_Sum_stage2_sub_cast_1;

  G12_b_out1 <= to_unsigned(16#1F#, 5);

  omega_Analog_signed <= signed(omega_Analog);

  G12_Multiply_o_cast <= signed(resize(G12_b_out1, 6));
  G12_Multiply_o_mul_temp <= G12_Multiply_o_cast * omega_Analog_signed;
  G12_Multiply_o_cast_1 <= G12_Multiply_o_mul_temp(36 DOWNTO 0);
  G12_Multiply_o_out1 <= G12_Multiply_o_cast_1(35 DOWNTO 16);

  G12_Sum_stage3_sub_cast <= resize(G12_Multiply_o_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 33);
  G12_Sum_stage3_sub_temp <= G12_Sum_op_stage2 - G12_Sum_stage3_sub_cast;
  G12_Sum_out1 <= G12_Sum_stage3_sub_temp(27 DOWNTO 0) & '0' & '0' & '0' & '0';

  invG12 <= std_logic_vector(G12_Sum_out1);

  G21_a_out1 <= to_unsigned(1470628, 32);

  G21_Mulitiply_Tc_mul_temp <= G21_a_out1 * no_limit_Tc_unsigned;
  G21_Mulitiply_Tc_out1 <= G21_Mulitiply_Tc_mul_temp(47 DOWNTO 24);

  G21_b_out1 <= to_unsigned(16#0018#, 16);

  G21_Multiply_o_cast <= signed(resize(G21_b_out1, 17));
  G21_Multiply_o_mul_temp <= G21_Multiply_o_cast * omega_Analog_signed;
  G21_Multiply_o_cast_1 <= G21_Multiply_o_mul_temp(47 DOWNTO 0);
  G21_Multiply_o_out1 <= unsigned(G21_Multiply_o_cast_1(31 DOWNTO 16));

  G21_Sum_stage2_add_cast <= signed(resize(G21_Mulitiply_Tc_out1, 26));
  G21_Sum_stage2_add_cast_1 <= signed(resize(G21_Multiply_o_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 26));
  G21_Sum_op_stage2 <= G21_Sum_stage2_add_cast + G21_Sum_stage2_add_cast_1;

  G21_c_out1 <= to_unsigned(16#0093#, 16);

  G21_Sum_stage3_sub_cast <= signed(resize(G21_c_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 26));
  G21_Sum_stage3_sub_temp <= G21_Sum_op_stage2 - G21_Sum_stage3_sub_cast;
  G21_Sum_out1 <= resize(G21_Sum_stage3_sub_temp & '0' & '0' & '0' & '0', 32);

  invG21 <= std_logic_vector(G21_Sum_out1);

  G22_a_out1 <= to_unsigned(16#0243#, 16);

  G22_Multiply_Tc_mul_temp <= for_G11_G22_out1 * G22_a_out1;
  G22_Multiply_Tc_out1 <= signed(G22_Multiply_Tc_mul_temp(47 DOWNTO 16));

  G22_b_out1 <= to_unsigned(16#BA72#, 16);

  G22_Sum_add_cast <= resize(G22_Multiply_Tc_out1, 33);
  G22_Sum_add_cast_1 <= signed(resize(G22_b_out1, 33));
  G22_Sum_add_temp <= G22_Sum_add_cast + G22_Sum_add_cast_1;
  G22_Sum_out1 <= G22_Sum_add_temp(31 DOWNTO 0);

  invG22 <= std_logic_vector(G22_Sum_out1);

END rtl;

