-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\MSDB_Control\invGF.vhd
-- Created: 2022-02-04 15:03:05
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: invGF
-- Source Path: MSDB_Control/Control_Sub/invGF
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY invGF IS
  PORT( omega_Analog                      :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        limit_Tc                          :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32_En32
        no_limit_Tc                       :   IN    std_logic_vector(31 DOWNTO 0);  -- ufix32_En32
        invGF11                           :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        invGF12                           :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
        invGF21                           :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
        invGF22                           :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En16
        );
END invGF;


ARCHITECTURE rtl OF invGF IS

  -- Signals
  SIGNAL GF11_a_out1                      : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL limit_Tc_unsigned                : unsigned(31 DOWNTO 0);  -- ufix32_En32
  SIGNAL for_GF11_GF22_out1               : unsigned(31 DOWNTO 0);  -- ufix32_En16
  SIGNAL GF11_Multiply_Tc_mul_temp        : unsigned(47 DOWNTO 0);  -- ufix48_En32
  SIGNAL GF11_Multiply_Tc_out1            : unsigned(31 DOWNTO 0);  -- ufix32_En16
  SIGNAL GF11_b_out1                      : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL GF11_Sum_sub_cast                : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL GF11_Sum_sub_cast_1              : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL GF11_Sum_sub_temp                : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL GF11_Sum_out1                    : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL GF12_c_out1                      : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL GF12_a_out1                      : unsigned(31 DOWNTO 0);  -- ufix32_En16
  SIGNAL no_limit_Tc_unsigned             : unsigned(31 DOWNTO 0);  -- ufix32_En32
  SIGNAL GF12_Mulitiply_Tc_mul_temp       : unsigned(63 DOWNTO 0);  -- ufix64_En48
  SIGNAL GF12_Mulitiply_Tc_out1           : unsigned(31 DOWNTO 0);  -- ufix32_En24
  SIGNAL GF12_Sum_stage2_sub_cast         : signed(32 DOWNTO 0);  -- sfix33_En24
  SIGNAL GF12_Sum_stage2_sub_cast_1       : signed(32 DOWNTO 0);  -- sfix33_En24
  SIGNAL GF12_Sum_op_stage2               : signed(32 DOWNTO 0);  -- sfix33_En24
  SIGNAL GF12_b_out1                      : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL omega_Analog_signed              : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL GF12_Multiply_o_cast             : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL GF12_Multiply_o_mul_temp         : signed(48 DOWNTO 0);  -- sfix49_En32
  SIGNAL GF12_Multiply_o_cast_1           : signed(47 DOWNTO 0);  -- sfix48_En32
  SIGNAL GF12_Multiply_o_out1             : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL GF12_Sum_stage3_add_cast         : signed(32 DOWNTO 0);  -- sfix33_En24
  SIGNAL GF12_Sum_stage3_add_temp         : signed(32 DOWNTO 0);  -- sfix33_En24
  SIGNAL GF12_Sum_out1                    : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL GF21_a_out1                      : unsigned(31 DOWNTO 0);  -- ufix32_En16
  SIGNAL GF21_Mulitiply_Tc_mul_temp       : unsigned(63 DOWNTO 0);  -- ufix64_En48
  SIGNAL GF21_Mulitiply_Tc_out1           : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL GF21_b_out1                      : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL GF21_Multiply_o_cast             : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL GF21_Multiply_o_mul_temp         : signed(48 DOWNTO 0);  -- sfix49_En32
  SIGNAL GF21_Multiply_o_cast_1           : signed(47 DOWNTO 0);  -- sfix48_En32
  SIGNAL GF21_Multiply_o_out1             : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL GF21_Sum_stage2_sub_cast         : signed(33 DOWNTO 0);  -- sfix34_En28
  SIGNAL GF21_Sum_stage2_sub_cast_1       : signed(33 DOWNTO 0);  -- sfix34_En28
  SIGNAL GF21_Sum_op_stage2               : signed(33 DOWNTO 0);  -- sfix34_En28
  SIGNAL GF21_c_out1                      : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL GF21_Sum_stage3_sub_cast         : signed(33 DOWNTO 0);  -- sfix34_En28
  SIGNAL GF21_Sum_stage3_sub_temp         : signed(33 DOWNTO 0);  -- sfix34_En28
  SIGNAL GF21_Sum_out1                    : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL G22_a_out1                       : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL GF22_Multiply_Tc_mul_temp        : unsigned(47 DOWNTO 0);  -- ufix48_En32
  SIGNAL GF22_Multiply_Tc_out1            : unsigned(31 DOWNTO 0);  -- ufix32_En16
  SIGNAL G22_b_out1                       : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL GF22_Sum_sub_cast                : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL GF22_Sum_sub_cast_1              : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL GF22_Sum_sub_temp                : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL GF22_Sum_out1                    : signed(31 DOWNTO 0);  -- sfix32_En16

BEGIN
  GF11_a_out1 <= to_unsigned(16#01C7#, 16);

  limit_Tc_unsigned <= unsigned(limit_Tc);

  for_GF11_GF22_output : PROCESS (limit_Tc_unsigned)
    VARIABLE c : unsigned(48 DOWNTO 0);
    VARIABLE div_temp : unsigned(48 DOWNTO 0);
  BEGIN
    div_temp := to_unsigned(0, 49);
    IF limit_Tc_unsigned = to_unsigned(0, 32) THEN 
      c := unsigned'("1111111111111111111111111111111111111111111111111");
    ELSE 
      div_temp := unsigned'("1000000000000000000000000000000000000000000000000") / limit_Tc_unsigned;
      c := div_temp;
    END IF;
    IF c(48 DOWNTO 32) /= "00000000000000000" THEN 
      for_GF11_GF22_out1 <= X"FFFFFFFF";
    ELSE 
      for_GF11_GF22_out1 <= c(31 DOWNTO 0);
    END IF;
  END PROCESS for_GF11_GF22_output;


  GF11_Multiply_Tc_mul_temp <= GF11_a_out1 * for_GF11_GF22_out1;
  GF11_Multiply_Tc_out1 <= GF11_Multiply_Tc_mul_temp(47 DOWNTO 16);

  GF11_b_out1 <= to_unsigned(16#B53C#, 16);

  GF11_Sum_sub_cast <= signed(resize(GF11_Multiply_Tc_out1, 33));
  GF11_Sum_sub_cast_1 <= signed(resize(GF11_b_out1, 33));
  GF11_Sum_sub_temp <= GF11_Sum_sub_cast - GF11_Sum_sub_cast_1;
  GF11_Sum_out1 <= GF11_Sum_sub_temp(31 DOWNTO 0);

  invGF11 <= std_logic_vector(GF11_Sum_out1);

  GF12_c_out1 <= to_unsigned(16#00B6#, 16);

  GF12_a_out1 <= to_unsigned(1871708, 32);

  no_limit_Tc_unsigned <= unsigned(no_limit_Tc);

  GF12_Mulitiply_Tc_mul_temp <= GF12_a_out1 * no_limit_Tc_unsigned;
  GF12_Mulitiply_Tc_out1 <= GF12_Mulitiply_Tc_mul_temp(55 DOWNTO 24);

  GF12_Sum_stage2_sub_cast <= signed(resize(GF12_c_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 33));
  GF12_Sum_stage2_sub_cast_1 <= signed(resize(GF12_Mulitiply_Tc_out1, 33));
  GF12_Sum_op_stage2 <= GF12_Sum_stage2_sub_cast - GF12_Sum_stage2_sub_cast_1;

  GF12_b_out1 <= to_unsigned(16#001E#, 16);

  omega_Analog_signed <= signed(omega_Analog);

  GF12_Multiply_o_cast <= signed(resize(GF12_b_out1, 17));
  GF12_Multiply_o_mul_temp <= GF12_Multiply_o_cast * omega_Analog_signed;
  GF12_Multiply_o_cast_1 <= GF12_Multiply_o_mul_temp(47 DOWNTO 0);
  GF12_Multiply_o_out1 <= unsigned(GF12_Multiply_o_cast_1(31 DOWNTO 16));

  GF12_Sum_stage3_add_cast <= signed(resize(GF12_Multiply_o_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 33));
  GF12_Sum_stage3_add_temp <= GF12_Sum_op_stage2 + GF12_Sum_stage3_add_cast;
  GF12_Sum_out1 <= GF12_Sum_stage3_add_temp(27 DOWNTO 0) & '0' & '0' & '0' & '0';

  invGF12 <= std_logic_vector(GF12_Sum_out1);

  GF21_a_out1 <= to_unsigned(1470628, 32);

  GF21_Mulitiply_Tc_mul_temp <= GF21_a_out1 * no_limit_Tc_unsigned;
  GF21_Mulitiply_Tc_out1 <= signed(GF21_Mulitiply_Tc_mul_temp(51 DOWNTO 20));

  GF21_b_out1 <= to_unsigned(16#0018#, 16);

  GF21_Multiply_o_cast <= signed(resize(GF21_b_out1, 17));
  GF21_Multiply_o_mul_temp <= GF21_Multiply_o_cast * omega_Analog_signed;
  GF21_Multiply_o_cast_1 <= GF21_Multiply_o_mul_temp(47 DOWNTO 0);
  GF21_Multiply_o_out1 <= GF21_Multiply_o_cast_1(35 DOWNTO 4);

  GF21_Sum_stage2_sub_cast <= resize(GF21_Mulitiply_Tc_out1, 34);
  GF21_Sum_stage2_sub_cast_1 <= resize(GF21_Multiply_o_out1, 34);
  GF21_Sum_op_stage2 <= GF21_Sum_stage2_sub_cast - GF21_Sum_stage2_sub_cast_1;

  GF21_c_out1 <= to_unsigned(16#0093#, 16);

  GF21_Sum_stage3_sub_cast <= signed(resize(GF21_c_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 34));
  GF21_Sum_stage3_sub_temp <= GF21_Sum_op_stage2 - GF21_Sum_stage3_sub_cast;
  GF21_Sum_out1 <= GF21_Sum_stage3_sub_temp(31 DOWNTO 0);

  invGF21 <= std_logic_vector(GF21_Sum_out1);

  G22_a_out1 <= to_unsigned(16#0243#, 16);

  GF22_Multiply_Tc_mul_temp <= for_GF11_GF22_out1 * G22_a_out1;
  GF22_Multiply_Tc_out1 <= GF22_Multiply_Tc_mul_temp(47 DOWNTO 16);

  G22_b_out1 <= to_unsigned(16#B632#, 16);

  GF22_Sum_sub_cast <= signed(resize(GF22_Multiply_Tc_out1, 33));
  GF22_Sum_sub_cast_1 <= signed(resize(G22_b_out1, 33));
  GF22_Sum_sub_temp <= GF22_Sum_sub_cast - GF22_Sum_sub_cast_1;
  GF22_Sum_out1 <= GF22_Sum_sub_temp(31 DOWNTO 0);

  invGF22 <= std_logic_vector(GF22_Sum_out1);

END rtl;

