-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\MSDB_Control\limit_Tc_and_no_limit_Tc.vhd
-- Created: 2022-02-04 15:03:05
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: limit_Tc_and_no_limit_Tc
-- Source Path: MSDB_Control/Control_Sub/limit_Tc and no_limit_Tc
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY limit_Tc_and_no_limit_Tc IS
  PORT( Tc_count_2500                     :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        limit_Tc                          :   OUT   std_logic_vector(31 DOWNTO 0);  -- ufix32_En32
        no_limit_Tc                       :   OUT   std_logic_vector(31 DOWNTO 0)  -- ufix32_En32
        );
END limit_Tc_and_no_limit_Tc;


ARCHITECTURE rtl OF limit_Tc_and_no_limit_Tc IS

  -- Signals
  SIGNAL Tc_count_2500_unsigned           : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Sampling_period_signed           : unsigned(31 DOWNTO 0);  -- ufix32_En32
  SIGNAL Tc_mulitply_mul_temp             : unsigned(47 DOWNTO 0);  -- ufix48_En32
  SIGNAL Tc_out                           : unsigned(31 DOWNTO 0);  -- ufix32_En32
  SIGNAL limit_5e_5                       : unsigned(31 DOWNTO 0);  -- ufix32_En32
  SIGNAL Compare_relop1                   : std_logic;
  SIGNAL Tc_limit_out                     : unsigned(31 DOWNTO 0);  -- ufix32_En32

BEGIN
  Tc_count_2500_unsigned <= unsigned(Tc_count_2500);

  Sampling_period_signed <= to_unsigned(344, 32);

  Tc_mulitply_mul_temp <= Tc_count_2500_unsigned * Sampling_period_signed;
  Tc_out <= Tc_mulitply_mul_temp(31 DOWNTO 0);

  limit_5e_5 <= to_unsigned(214748, 32);

  
  Compare_relop1 <= '1' WHEN Tc_out >= limit_5e_5 ELSE
      '0';

  
  Tc_limit_out <= limit_5e_5 WHEN Compare_relop1 = '0' ELSE
      Tc_out;

  limit_Tc <= std_logic_vector(Tc_limit_out);

  no_limit_Tc <= std_logic_vector(Tc_out);

END rtl;

