-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\MSDB_Control\MSDB_Control.vhd
-- Created: 2022-02-04 15:03:05
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 8e-08
-- Target subsystem base rate: 8e-08
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MSDB_Control
-- Source Path: MSDB_Control
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY MSDB_Control IS
  PORT( Omega_Rpm_Digital                 :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        Count_2500                        :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        Id                                :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        Iq                                :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        Idref                             :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        Iqref                             :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        Vd                                :   OUT   std_logic_vector(15 DOWNTO 0);  -- int16
        Vq                                :   OUT   std_logic_vector(15 DOWNTO 0)  -- int16
        );
END MSDB_Control;


ARCHITECTURE rtl OF MSDB_Control IS

  -- Component Declarations
  COMPONENT Control_Sub
    PORT( Omega_Rpm_Digital               :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
          Count_2500                      :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          Id                              :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
          Iq                              :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
          Idref                           :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
          Iqref                           :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
          U1MDBd                          :   OUT   std_logic_vector(15 DOWNTO 0);  -- int16
          U1MDBq                          :   OUT   std_logic_vector(15 DOWNTO 0)  -- int16
          );
  END COMPONENT;

--  -- Component Configuration Statements
--  FOR ALL : Control_Sub
--    USE ENTITY work.Control_Sub(rtl);

  -- Signals
  SIGNAL Control_Sub_out1                 : std_logic_vector(15 DOWNTO 0);  -- ufix16
  SIGNAL Control_Sub_out2                 : std_logic_vector(15 DOWNTO 0);  -- ufix16

BEGIN
  u_Control_Sub : Control_Sub
    PORT MAP( Omega_Rpm_Digital => Omega_Rpm_Digital,  -- int16
              Count_2500 => Count_2500,  -- uint16
              Id => Id,  -- int16
              Iq => Iq,  -- int16
              Idref => Idref,  -- int16
              Iqref => Iqref,  -- int16
              U1MDBd => Control_Sub_out1,  -- int16
              U1MDBq => Control_Sub_out2  -- int16
              );

  Vd <= Control_Sub_out1;

  Vq <= Control_Sub_out2;

END rtl;

