-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\MSDB_Control\PWM_Gain.vhd
-- Created: 2022-02-04 15:03:05
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: PWM_Gain
-- Source Path: MSDB_Control/Control_Sub/PWM_Gain
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY PWM_Gain IS
  PORT( Vd                                :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        Vq                                :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        U1MDBd                            :   OUT   std_logic_vector(15 DOWNTO 0);  -- int16
        U1MDBq                            :   OUT   std_logic_vector(15 DOWNTO 0)  -- int16
        );
END PWM_Gain;


ARCHITECTURE rtl OF PWM_Gain IS

  -- Signals
  SIGNAL Vd_signed                        : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL E_Gain_out1                      : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL for_Vd1_cast                     : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL for_Vd1_mul_temp                 : signed(48 DOWNTO 0);  -- sfix49_En32
  SIGNAL for_Vd1_cast_1                   : signed(47 DOWNTO 0);  -- sfix48_En32
  SIGNAL for_Vd1_out1                     : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL PWM_Gain_out1                    : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL for_Vd_cast                      : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL for_Vd_mul_temp                  : signed(48 DOWNTO 0);  -- sfix49_En16
  SIGNAL for_Vd_cast_1                    : signed(47 DOWNTO 0);  -- sfix48_En16
  SIGNAL for_Vd_out1                      : signed(47 DOWNTO 0);  -- sfix48_En24
  SIGNAL dtc_out                          : signed(15 DOWNTO 0);  -- int16
  SIGNAL limit_Vd_out1                    : signed(15 DOWNTO 0);  -- int16
  SIGNAL Vq_signed                        : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL for_Vd2_cast                     : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL for_Vd2_mul_temp                 : signed(48 DOWNTO 0);  -- sfix49_En32
  SIGNAL for_Vd2_cast_1                   : signed(47 DOWNTO 0);  -- sfix48_En32
  SIGNAL for_Vd2_out1                     : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL for_Vq_cast                      : signed(16 DOWNTO 0);  -- sfix17
  SIGNAL for_Vq_mul_temp                  : signed(48 DOWNTO 0);  -- sfix49_En16
  SIGNAL for_Vq_cast_1                    : signed(47 DOWNTO 0);  -- sfix48_En16
  SIGNAL for_Vq_out1                      : signed(47 DOWNTO 0);  -- sfix48_En24
  SIGNAL dtc_out_1                        : signed(15 DOWNTO 0);  -- int16
  SIGNAL limit_Vq_out1                    : signed(15 DOWNTO 0);  -- int16

BEGIN
  Vd_signed <= signed(Vd);

  E_Gain_out1 <= to_unsigned(16#028F#, 16);

  for_Vd1_cast <= signed(resize(E_Gain_out1, 17));
  for_Vd1_mul_temp <= Vd_signed * for_Vd1_cast;
  for_Vd1_cast_1 <= for_Vd1_mul_temp(47 DOWNTO 0);
  for_Vd1_out1 <= for_Vd1_cast_1(47 DOWNTO 16);

  PWM_Gain_out1 <= to_unsigned(16#7EF4#, 16);

  for_Vd_cast <= signed(resize(PWM_Gain_out1, 17));
  for_Vd_mul_temp <= for_Vd1_out1 * for_Vd_cast;
  for_Vd_cast_1 <= for_Vd_mul_temp(47 DOWNTO 0);
  for_Vd_out1 <= for_Vd_cast_1(39 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';

  
  dtc_out <= X"7FFF" WHEN (for_Vd_out1(47) = '0') AND (for_Vd_out1(46 DOWNTO 39) /= "00000000") ELSE
      X"8000" WHEN (for_Vd_out1(47) = '1') AND (for_Vd_out1(46 DOWNTO 39) /= "11111111") ELSE
      for_Vd_out1(39 DOWNTO 24);

  
  limit_Vd_out1 <= to_signed(16#7EF4#, 16) WHEN dtc_out > to_signed(16#7EF4#, 16) ELSE
      to_signed(-16#7EF4#, 16) WHEN dtc_out < to_signed(-16#7EF4#, 16) ELSE
      dtc_out;

  U1MDBd <= std_logic_vector(limit_Vd_out1);

  Vq_signed <= signed(Vq);

  for_Vd2_cast <= signed(resize(E_Gain_out1, 17));
  for_Vd2_mul_temp <= for_Vd2_cast * Vq_signed;
  for_Vd2_cast_1 <= for_Vd2_mul_temp(47 DOWNTO 0);
  for_Vd2_out1 <= for_Vd2_cast_1(47 DOWNTO 16);

  for_Vq_cast <= signed(resize(PWM_Gain_out1, 17));
  for_Vq_mul_temp <= for_Vq_cast * for_Vd2_out1;
  for_Vq_cast_1 <= for_Vq_mul_temp(47 DOWNTO 0);
  for_Vq_out1 <= for_Vq_cast_1(39 DOWNTO 0) & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0';

  
  dtc_out_1 <= X"7FFF" WHEN (for_Vq_out1(47) = '0') AND (for_Vq_out1(46 DOWNTO 39) /= "00000000") ELSE
      X"8000" WHEN (for_Vq_out1(47) = '1') AND (for_Vq_out1(46 DOWNTO 39) /= "11111111") ELSE
      for_Vq_out1(39 DOWNTO 24);

  
  limit_Vq_out1 <= to_signed(16#7EF4#, 16) WHEN dtc_out_1 > to_signed(16#7EF4#, 16) ELSE
      to_signed(-16#7EF4#, 16) WHEN dtc_out_1 < to_signed(-16#7EF4#, 16) ELSE
      dtc_out_1;

  U1MDBq <= std_logic_vector(limit_Vq_out1);

END rtl;

