-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\MSDB_Control\Vdq_ref.vhd
-- Created: 2022-02-04 15:03:05
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Vdq_ref
-- Source Path: MSDB_Control/Control_Sub/Vdq_ref
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Vdq_ref IS
  PORT( invG11                            :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        invG12                            :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
        invG21                            :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
        invG22                            :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        invGF11                           :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        invGF12                           :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
        invGF21                           :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En28
        invGF22                           :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        Id                                :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        Iq                                :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        Idref                             :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        Iqref                             :   IN    std_logic_vector(15 DOWNTO 0);  -- int16
        Omega_Sgn                         :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        Vd                                :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En16
        Vq                                :   OUT   std_logic_vector(31 DOWNTO 0)  -- sfix32_En16
        );
END Vdq_ref;


ARCHITECTURE rtl OF Vdq_ref IS

  -- Signals
  SIGNAL invG11_signed                    : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL Idref_signed                     : signed(15 DOWNTO 0);  -- int16
  SIGNAL I_Gain1_out1                     : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL Idref_7_38_cast                  : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL Idref_7_38_mul_temp              : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL Idref_7_38_out1                  : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL I_Gain_out1                      : unsigned(15 DOWNTO 0);  -- ufix16_En16
  SIGNAL Idref_7FF_cast                   : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL Idref_7FF_mul_temp               : signed(48 DOWNTO 0);  -- sfix49_En32
  SIGNAL Idref_7FF_cast_1                 : signed(47 DOWNTO 0);  -- sfix48_En32
  SIGNAL Idref_7FF_out1                   : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL G11_Idref_mul_temp               : signed(63 DOWNTO 0);  -- sfix64_En32
  SIGNAL G11_Idref_out1                   : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL invG12_signed                    : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL Iqref_signed                     : signed(15 DOWNTO 0);  -- int16
  SIGNAL Iqref_7_38_cast                  : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL Iqref_7_38_mul_temp              : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL Iqref_7_38_out1                  : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL Iqref_7FF_cast                   : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL Iqref_7FF_mul_temp               : signed(48 DOWNTO 0);  -- sfix49_En32
  SIGNAL Iqref_7FF_cast_1                 : signed(47 DOWNTO 0);  -- sfix48_En32
  SIGNAL Iqref_7FF_out1                   : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL G12_Iqref_mul_temp               : signed(63 DOWNTO 0);  -- sfix64_En44
  SIGNAL G12_Iqref_out1                   : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL Vdref_stage2_add_cast            : signed(41 DOWNTO 0);  -- sfix42_En24
  SIGNAL Vdref_stage2_add_cast_1          : signed(41 DOWNTO 0);  -- sfix42_En24
  SIGNAL Vdref_op_stage2                  : signed(41 DOWNTO 0);  -- sfix42_En24
  SIGNAL invGF11_signed                   : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL Id_signed                        : signed(15 DOWNTO 0);  -- int16
  SIGNAL Id_7_38_cast                     : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL Id_7_38_mul_temp                 : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL Id_7_38_out1                     : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL Id_7FF_cast                      : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL Id_7FF_mul_temp                  : signed(48 DOWNTO 0);  -- sfix49_En32
  SIGNAL Id_7FF_cast_1                    : signed(47 DOWNTO 0);  -- sfix48_En32
  SIGNAL Id_7FF_out1                      : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL GF11_Id_mul_temp                 : signed(63 DOWNTO 0);  -- sfix64_En32
  SIGNAL GF11_Id_out1                     : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL Vdref_stage3_sub_cast            : signed(41 DOWNTO 0);  -- sfix42_En24
  SIGNAL Vdref_op_stage3                  : signed(41 DOWNTO 0);  -- sfix42_En24
  SIGNAL invGF12_signed                   : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL Iq_signed                        : signed(15 DOWNTO 0);  -- int16
  SIGNAL Iq_7_38_cast                     : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL Iq_7_38_mul_temp                 : signed(32 DOWNTO 0);  -- sfix33_En16
  SIGNAL Iq_7_38_out1                     : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL Iq_7FF_cast                      : signed(16 DOWNTO 0);  -- sfix17_En16
  SIGNAL Iq_7FF_mul_temp                  : signed(48 DOWNTO 0);  -- sfix49_En32
  SIGNAL Iq_7FF_cast_1                    : signed(47 DOWNTO 0);  -- sfix48_En32
  SIGNAL Iq_7FF_out1                      : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL GF12_Iq_mul_temp                 : signed(63 DOWNTO 0);  -- sfix64_En44
  SIGNAL GF12_Iq_out1                     : signed(31 DOWNTO 0);  -- sfix32_En24
  SIGNAL Vdref_stage4_sub_cast            : signed(41 DOWNTO 0);  -- sfix42_En24
  SIGNAL Vdref_stage4_sub_temp            : signed(41 DOWNTO 0);  -- sfix42_En24
  SIGNAL Vdref_out1                       : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL invG21_signed                    : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL G21_Idref_mul_temp               : signed(63 DOWNTO 0);  -- sfix64_En44
  SIGNAL G21_Idref_out1                   : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL invG22_signed                    : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL G22_Iqref_mul_temp               : signed(63 DOWNTO 0);  -- sfix64_En32
  SIGNAL G22_Iqref_out1                   : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL Vqref_stage2_add_cast            : signed(33 DOWNTO 0);  -- sfix34_En16
  SIGNAL Vqref_stage2_add_cast_1          : signed(33 DOWNTO 0);  -- sfix34_En16
  SIGNAL Vqref_op_stage2                  : signed(33 DOWNTO 0);  -- sfix34_En16
  SIGNAL invGF21_signed                   : signed(31 DOWNTO 0);  -- sfix32_En28
  SIGNAL GF21_Id_mul_temp                 : signed(63 DOWNTO 0);  -- sfix64_En44
  SIGNAL GF21_Id_out1                     : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL Vqref_stage3_sub_cast            : signed(33 DOWNTO 0);  -- sfix34_En16
  SIGNAL Vqref_op_stage3                  : signed(33 DOWNTO 0);  -- sfix34_En16
  SIGNAL invGF22_signed                   : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL GF22_Iq_mul_temp                 : signed(63 DOWNTO 0);  -- sfix64_En32
  SIGNAL GF22_Iq_out1                     : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL Vqref_stage4_sub_cast            : signed(33 DOWNTO 0);  -- sfix34_En16
  SIGNAL Vqref_stage4_sub_temp            : signed(33 DOWNTO 0);  -- sfix34_En16
  SIGNAL Vqref_out1                       : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL Omega_Sgn_signed                 : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL Gain_mul_temp                    : signed(63 DOWNTO 0);  -- sfix64_En49
  SIGNAL Gain_out1                        : signed(31 DOWNTO 0);  -- sfix32_En16
  SIGNAL Vqref_out1_1                     : signed(31 DOWNTO 0);  -- sfix32_En16

BEGIN
  invG11_signed <= signed(invG11);

  Idref_signed <= signed(Idref);

  I_Gain1_out1 <= to_unsigned(16#22B0#, 16);

  Idref_7_38_cast <= signed(resize(I_Gain1_out1, 17));
  Idref_7_38_mul_temp <= Idref_signed * Idref_7_38_cast;
  Idref_7_38_out1 <= Idref_7_38_mul_temp(31 DOWNTO 0);

  I_Gain_out1 <= to_unsigned(16#0020#, 16);

  Idref_7FF_cast <= signed(resize(I_Gain_out1, 17));
  Idref_7FF_mul_temp <= Idref_7_38_out1 * Idref_7FF_cast;
  Idref_7FF_cast_1 <= Idref_7FF_mul_temp(47 DOWNTO 0);
  Idref_7FF_out1 <= Idref_7FF_cast_1(47 DOWNTO 16);

  G11_Idref_mul_temp <= invG11_signed * Idref_7FF_out1;
  G11_Idref_out1 <= G11_Idref_mul_temp(47 DOWNTO 16);

  invG12_signed <= signed(invG12);

  Iqref_signed <= signed(Iqref);

  Iqref_7_38_cast <= signed(resize(I_Gain1_out1, 17));
  Iqref_7_38_mul_temp <= Iqref_signed * Iqref_7_38_cast;
  Iqref_7_38_out1 <= Iqref_7_38_mul_temp(31 DOWNTO 0);

  Iqref_7FF_cast <= signed(resize(I_Gain_out1, 17));
  Iqref_7FF_mul_temp <= Iqref_7_38_out1 * Iqref_7FF_cast;
  Iqref_7FF_cast_1 <= Iqref_7FF_mul_temp(47 DOWNTO 0);
  Iqref_7FF_out1 <= Iqref_7FF_cast_1(47 DOWNTO 16);

  G12_Iqref_mul_temp <= invG12_signed * Iqref_7FF_out1;
  G12_Iqref_out1 <= G12_Iqref_mul_temp(51 DOWNTO 20);

  Vdref_stage2_add_cast <= resize(G11_Idref_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 42);
  Vdref_stage2_add_cast_1 <= resize(G12_Iqref_out1, 42);
  Vdref_op_stage2 <= Vdref_stage2_add_cast + Vdref_stage2_add_cast_1;

  invGF11_signed <= signed(invGF11);

  Id_signed <= signed(Id);

  Id_7_38_cast <= signed(resize(I_Gain1_out1, 17));
  Id_7_38_mul_temp <= Id_signed * Id_7_38_cast;
  Id_7_38_out1 <= Id_7_38_mul_temp(31 DOWNTO 0);

  Id_7FF_cast <= signed(resize(I_Gain_out1, 17));
  Id_7FF_mul_temp <= Id_7_38_out1 * Id_7FF_cast;
  Id_7FF_cast_1 <= Id_7FF_mul_temp(47 DOWNTO 0);
  Id_7FF_out1 <= Id_7FF_cast_1(47 DOWNTO 16);

  GF11_Id_mul_temp <= invGF11_signed * Id_7FF_out1;
  GF11_Id_out1 <= GF11_Id_mul_temp(47 DOWNTO 16);

  Vdref_stage3_sub_cast <= resize(GF11_Id_out1 & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0', 42);
  Vdref_op_stage3 <= Vdref_op_stage2 - Vdref_stage3_sub_cast;

  invGF12_signed <= signed(invGF12);

  Iq_signed <= signed(Iq);

  Iq_7_38_cast <= signed(resize(I_Gain1_out1, 17));
  Iq_7_38_mul_temp <= Iq_signed * Iq_7_38_cast;
  Iq_7_38_out1 <= Iq_7_38_mul_temp(31 DOWNTO 0);

  Iq_7FF_cast <= signed(resize(I_Gain_out1, 17));
  Iq_7FF_mul_temp <= Iq_7_38_out1 * Iq_7FF_cast;
  Iq_7FF_cast_1 <= Iq_7FF_mul_temp(47 DOWNTO 0);
  Iq_7FF_out1 <= Iq_7FF_cast_1(47 DOWNTO 16);

  GF12_Iq_mul_temp <= invGF12_signed * Iq_7FF_out1;
  GF12_Iq_out1 <= GF12_Iq_mul_temp(51 DOWNTO 20);

  Vdref_stage4_sub_cast <= resize(GF12_Iq_out1, 42);
  Vdref_stage4_sub_temp <= Vdref_op_stage3 - Vdref_stage4_sub_cast;
  Vdref_out1 <= Vdref_stage4_sub_temp(39 DOWNTO 8);

  Vd <= std_logic_vector(Vdref_out1);

  invG21_signed <= signed(invG21);

  G21_Idref_mul_temp <= invG21_signed * Idref_7FF_out1;
  G21_Idref_out1 <= G21_Idref_mul_temp(59 DOWNTO 28);

  invG22_signed <= signed(invG22);

  G22_Iqref_mul_temp <= invG22_signed * Iqref_7FF_out1;
  G22_Iqref_out1 <= G22_Iqref_mul_temp(47 DOWNTO 16);

  Vqref_stage2_add_cast <= resize(G21_Idref_out1, 34);
  Vqref_stage2_add_cast_1 <= resize(G22_Iqref_out1, 34);
  Vqref_op_stage2 <= Vqref_stage2_add_cast + Vqref_stage2_add_cast_1;

  invGF21_signed <= signed(invGF21);

  GF21_Id_mul_temp <= invGF21_signed * Id_7FF_out1;
  GF21_Id_out1 <= GF21_Id_mul_temp(59 DOWNTO 28);

  Vqref_stage3_sub_cast <= resize(GF21_Id_out1, 34);
  Vqref_op_stage3 <= Vqref_op_stage2 - Vqref_stage3_sub_cast;

  invGF22_signed <= signed(invGF22);

  GF22_Iq_mul_temp <= invGF22_signed * Iq_7FF_out1;
  GF22_Iq_out1 <= GF22_Iq_mul_temp(47 DOWNTO 16);

  Vqref_stage4_sub_cast <= resize(GF22_Iq_out1, 34);
  Vqref_stage4_sub_temp <= Vqref_op_stage3 - Vqref_stage4_sub_cast;
  Vqref_out1 <= Vqref_stage4_sub_temp(31 DOWNTO 0);

  Omega_Sgn_signed <= signed(Omega_Sgn);

  Gain_mul_temp <= to_signed(1644350764, 32) * Omega_Sgn_signed;
  Gain_out1 <= resize(Gain_mul_temp(63 DOWNTO 33), 32);

  Vqref_out1_1 <= Vqref_out1 + Gain_out1;

  Vq <= std_logic_vector(Vqref_out1_1);

END rtl;

